SHELL = /bin/bash
CC = gcc

DEBUGFLAGS  = -D__DEBUG_ON__
CFLAGS      = -std=c99 \
              -D_BSD_SOURCE \
              -O2 \
              $(DEBUGFLAGS)
LDFLAGS     = -lpthread \

SOURCES=$(shell echo src/*.c)
OBJECTS=$(SOURCES:.c=.o)
EXECUTABLE=comio2

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@

clean:
	-rm -f $(OBJECTS)
