SHELL = /bin/bash

TECHNO=linux
EXECUTABLE=hfbuttons-i2crelays
XPLLIB=$(TECHNO)_xPL.a
XPLLIBDIR=libraries/xPLLib
COMMON=common

CC = gcc

all:
	cd $(XPLLIBDIR) ; make TECHNO=$(TECHNO)
	cd $(XPLLIBDIR)/examples ; make TECHNO=$(TECHNO)
	cd $(COMMON) ; make EXECUTABLE=$(EXECUTABLE) TECHNO=$(TECHNO) CC=$(CC)

clean: cleancommon
	cd $(XPLLIBDIR) ; make TECHNO=$(TECHNO) clean
	cd $(XPLLIBDIR)/examples ; make TECHNO=$(TECHNO) clean
 
cleancommon:
	cd $(COMMON) ; make TECHNO=$(TECHNO) clean
