SHELL = /bin/bash

TECHNO=linux
EXECUTABLE=hfbuttons-i2crelays
XPLLIB=xPL.a
XPLLIBDIR=$(TECHNO)/xPLLib
COMMON=common

CC = gcc

all:
	cd $(XPLLIBDIR) ; make
	cd $(COMMON) ; make EXECUTABLE=$(EXECUTABLE) TECHNO=$(TECHNO) CC=$(CC)

clean: cleancommon
	cd $(XPLLIBDIR) ; make clean
 
cleancommon:
	cd $(COMMON) ; make TECHNO=$(TECHNO) clean
